// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Kraken")]
[assembly: AssemblyProductAttribute("kraken.NET 4.5")]
[assembly: AssemblyDescriptionAttribute("The official Kraken.io .Net client")]
[assembly: AssemblyVersionAttribute("0.2.0.0")]
[assembly: AssemblyFileVersionAttribute("0.2.0.0")]
[assembly: AssemblyCopyrightAttribute("2017")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Kraken";
        internal const System.String AssemblyProduct = "kraken.NET 4.5";
        internal const System.String AssemblyDescription = "The official Kraken.io .Net client";
        internal const System.String AssemblyVersion = "0.2.0.0";
        internal const System.String AssemblyFileVersion = "0.2.0.0";
        internal const System.String AssemblyCopyright = "2017";
    }
}
